import { createClient } from '@supabase/supabase-js';
const supabase=createClient('https://jpfnhwolttfisawfthbf.supabase.co','sb_publishable_vsHZotBHUEePBvunVgTWWQ_fIImlhYY',{auth:{persistSession:true,autoRefreshToken:true,storageKey:'lancers-chapel-session'}});
const CHECK=[{milestone:1,icon:'👋',name:'SHOWED UP'},{milestone:7,icon:'🎯',name:'CONSISTENT'},{milestone:10,icon:'💪',name:'TEN STRONG'},{milestone:30,icon:'🧱',name:'BUILT A RHYTHM'},{milestone:60,icon:'⚙️',name:'DIALED IN'},{milestone:75,icon:'🥇',name:'STEADFAST'},{milestone:100,icon:'💯',name:'100 STRONG'}];
const BIBLE=[{milestone:1,icon:'🌱',name:'PLANTED'},{milestone:7,icon:'📖',name:'ONE WEEK IN THE WORD'},{milestone:10,icon:'🪴',name:'ROOTED'},{milestone:30,icon:'🌳',name:'GROWING DEEP'},{milestone:60,icon:'🧭',name:'GUIDED BY THE WORD'},{milestone:75,icon:'⚔️',name:'SHARPENED'},{milestone:100,icon:'🪨',name:'BUILT ON THE ROCK'}];
const THREE=[{milestone:1,icon:'🟠',name:'FIRST STEP'},{milestone:7,icon:'🔥',name:'ONE WEEK'},{milestone:25,icon:'⚡',name:'LOCKED IN'},{milestone:40,icon:'🛡️',name:'BUILT DIFFERENT'},{milestone:50,icon:'🏆',name:'FIFTY STRONG'},{milestone:75,icon:'💎',name:'ALL IN'},{milestone:100,icon:'🐐',name:'GOAT'},{milestone:125,icon:'👑',name:'ELITE'},{milestone:150,icon:'🦁',name:'RELENTLESS'},{milestone:200,icon:'🏔️',name:'SUMMIT'}];let busy=false;
function day(date=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).format(date)}
function streak(raw){const days=[...new Set((raw||[]).filter(Boolean))].sort().reverse();let c=new Date(`${day()}T12:00:00`),n=0;if(!days.includes(day()))c.setDate(c.getDate()-1);for(const d of days){const e=day(c);if(d===e){n++;c.setDate(c.getDate()-1)}else if(d<e)break}return n}
function badgeIcons(track,current,big=false){const got=track.filter(b=>b.milestone<=current);return got.length?got.map(b=>`<span class="streak-earned-badge ${big?'big':''}" title="${b.name}">${b.icon}</span>`).join(''):'<span class="streak-no-badges">No badges yet</span>'}
function card(title,current,track,big=false){const next=track.find(b=>b.milestone>current);return `<section class="streak-card ${big?'all-three-card':''}"><div class="streak-card-top"><div><span class="streak-kicker">${title}</span><strong>${current} day${current===1?'':'s'}</strong></div>${next?`<div class="streak-next"><small>NEXT</small><span>${next.icon}</span><b>${next.milestone}</b></div>`:'<div class="streak-next complete"><small>MAX</small><span>🏆</span></div>'}</div><div class="streak-earned">${badgeIcons(track,current,big)}</div>${next?`<div class="streak-next-copy">Next badge: <b>${next.name}</b> at ${next.milestone} days</div>`:'<div class="streak-next-copy">All badges earned</div>'}</section>`}
function styles(){if(document.getElementById('checkin-badges-css'))return;const s=document.createElement('style');s.id='checkin-badges-css';s.textContent=`.home-milestones,.checkin-achievements,#home-badges-card,#badge-detail-pop{display:none!important}.streak-cards-wrap{margin:14px 16px 22px;display:grid;gap:12px}.streak-card{background:#141414;border:1px solid #2d2d2d;border-radius:18px;padding:16px}.streak-card.all-three-card{border-color:#5a351c;background:linear-gradient(145deg,#151515,#1c130d)}.streak-card-top{display:flex;justify-content:space-between;align-items:center;gap:12px}.streak-card-top>div:first-child{display:flex;flex-direction:column}.streak-kicker{font-size:9px;letter-spacing:.12em;font-weight:900;color:#f47a22}.streak-card-top strong{font-size:24px;line-height:1.05;margin-top:4px}.streak-next{display:grid;grid-template-columns:auto auto;grid-template-rows:auto auto;align-items:center;column-gap:5px;text-align:right}.streak-next small{grid-column:1/3;font-size:7px;letter-spacing:.12em;color:#777}.streak-next span{font-size:22px}.streak-next b{font-size:13px;color:#f3a264}.streak-earned{display:flex;flex-wrap:wrap;align-items:center;gap:8px;margin-top:13px;padding-top:12px;border-top:1px solid #292929}.streak-earned-badge{width:39px;height:39px;border-radius:50%;border:1px solid #5b371f;background:#20150d;display:grid;place-items:center;font-size:20px;box-shadow:inset 0 0 0 2px #111}.streak-earned-badge.big{width:52px;height:52px;font-size:27px;border:2px solid #ef6c00;box-shadow:inset 0 0 0 3px #111}.streak-no-badges{font-size:10px;color:#777}.streak-next-copy{font-size:9px;color:#888;margin-top:10px}.streak-next-copy b{color:#ddd}.all-three-card .streak-next-copy b{color:#f3a264}`;document.head.appendChild(s)}
async function render(){if(busy)return;const box=document.querySelector('.checkin');if(!box)return;busy=true;try{document.querySelectorAll('.checkin-achievements,.home-milestones,#home-badges-card,#badge-detail-pop').forEach(el=>el.remove());const {data:{session}}=await supabase.auth.getSession();if(!session)return;const [{data:checks},{data:actions},{data:threeDays}]=await Promise.all([supabase.from('checkins').select('checkin_day,created_at').eq('user_id',session.user.id).order('created_at',{ascending:false}).limit(260),supabase.from('daily_spiritual_actions').select('action_date,read_bible').eq('user_id',session.user.id).order('action_date',{ascending:false}).limit(260),supabase.from('daily_three_completions').select('completion_day').eq('user_id',session.user.id).order('completion_day',{ascending:false}).limit(260)]);const checkDays=(checks||[]).map(x=>x.checkin_day||day(new Date(x.created_at))),bibleDays=(actions||[]).filter(x=>x.read_bible).map(x=>x.action_date),allThreeDays=(threeDays||[]).map(x=>x.completion_day),cs=streak(checkDays),bs=streak(bibleDays),ts=streak(allThreeDays);let wrap=document.getElementById('streak-cards-wrap');if(!wrap){wrap=document.createElement('div');wrap.id='streak-cards-wrap';wrap.className='streak-cards-wrap'}box.insertAdjacentElement('afterend',wrap);wrap.innerHTML=card('CHECK-IN STREAK',cs,CHECK)+card('BIBLE STREAK',bs,BIBLE)+card('ALL 3 STREAK',ts,THREE,true)}finally{busy=false}}
styles();window.addEventListener('load',()=>setTimeout(render,800));supabase.auth.onAuthStateChange(()=>setTimeout(render,300));setTimeout(render,500);setInterval(render,4000);
