import { createClient } from '@supabase/supabase-js';
const supabase=createClient('https://jpfnhwolttfisawfthbf.supabase.co','sb_publishable_vsHZotBHUEePBvunVgTWWQ_fIImlhYY',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'lancers-chapel-session'}});

function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function addStyles(){if(document.getElementById('core-fixes-css'))return;const s=document.createElement('style');s.id='core-fixes-css';s.textContent=`.core-profile-menu{position:fixed;inset:0;background:rgba(0,0,0,.82);z-index:50000;display:flex;align-items:flex-start;justify-content:flex-end;padding:74px 14px 14px}.core-profile-panel{width:min(390px,calc(100vw - 28px));max-height:82vh;overflow:auto;background:#151515;border:1px solid #333;border-radius:18px;padding:18px;color:#fff}.core-profile-panel h2{margin:4px 0 16px}.core-profile-panel>button{width:100%;border:1px solid #343434;border-radius:14px;background:#1a1a1a;color:#fff;font-weight:900;padding:16px;text-align:left;margin:10px 0}.core-profile-panel>button.primary{background:#ef6c00;color:#111;border-color:#ef6c00}.core-profile-panel>button.danger{color:#ff8a8a}.core-profile-form{display:grid;gap:10px}.core-profile-form label{display:grid;gap:5px;font-size:11px;color:#aaa;font-weight:800}.core-profile-form input,.core-profile-form textarea{width:100%;box-sizing:border-box;border:1px solid #3b3b3b;border-radius:10px;background:#0f0f0f;color:#fff;padding:11px;font:inherit}.core-profile-form textarea{min-height:76px}.core-profile-form button{border:0;border-radius:11px;background:#ef6c00;color:#111;font-weight:900;padding:13px}.core-rsvp{margin-top:18px;padding-top:16px;border-top:1px solid rgba(255,255,255,.12)}.core-rsvp h3{margin:0 0 8px}.core-rsvp-summary{display:flex;gap:14px;margin-bottom:8px}.core-rsvp-summary b{color:#65d483}.core-rsvp-summary span{color:#ff7777}.core-rsvp-list{display:grid;gap:5px;font-size:14px}`;document.head.appendChild(s)}

function fixAdminJersey(){const gate=document.querySelector('.gate');if(!gate)return;const inputs=[...gate.querySelectorAll('input')];const last=inputs.find(i=>i.placeholder==='Last name');const jersey=inputs.find(i=>i.placeholder==='Jersey number');if(!last||!jersey)return;const admin=last.value.trim().toLowerCase()==='lingbloom';jersey.required=!admin;if(admin){jersey.removeAttribute('required');jersey.value='';jersey.style.setProperty('display','none','important');jersey.setAttribute('aria-hidden','true');jersey.tabIndex=-1}else{jersey.setAttribute('required','');jersey.style.removeProperty('display');jersey.removeAttribute('aria-hidden');jersey.tabIndex=0}}

async function openProfile(){addStyles();document.getElementById('core-profile-menu')?.remove();const {data:{session}}=await supabase.auth.getSession();if(!session)return;const {data:p}=await supabase.from('profiles').select('display_name,role').eq('id',session.user.id).maybeSingle();const root=document.createElement('div');root.id='core-profile-menu';root.className='core-profile-menu';root.innerHTML=`<div class="core-profile-panel"><span class="eyebrow">PROFILE</span><h2>${esc(p?.display_name||'My Profile')}</h2><button class="primary update">Update Profile</button><button class="refs">Reflections</button><button class="danger out">Sign Out</button></div>`;root.onclick=e=>{if(e.target===root)root.remove()};root.querySelector('.out').onclick=async()=>{await supabase.auth.signOut();location.reload()};root.querySelector('.update').onclick=()=>showUpdate(root,session.user.id,p);root.querySelector('.refs').onclick=()=>showRefs(root,session.user.id);document.body.appendChild(root)}
async function showUpdate(root,userId,p){const panel=root.querySelector('.core-profile-panel');const {data:d}=await supabase.from('player_profiles').select('*').eq('user_id',userId).maybeSingle();const v=d||{};panel.innerHTML=`<button class="back">← Profile</button><span class="eyebrow">UPDATE PROFILE</span><h2>${esc(p?.display_name||'My Profile')}</h2><form class="core-profile-form"><label>Hometown<input name="hometown" value="${esc(v.hometown||'')}"></label><label>Pregame routine<textarea name="pregame_routine">${esc(v.pregame_routine||'')}</textarea></label><label>Pregame song<input name="pregame_song" value="${esc(v.pregame_song||'')}"></label><label>Favorite snack<input name="favorite_snack" value="${esc(v.favorite_snack||'')}"></label><label>Favorite restaurant<input name="favorite_restaurant" value="${esc(v.favorite_restaurant||'')}"></label><label>Something teammates should know<textarea name="teammate_fact">${esc(v.teammate_fact||'')}</textarea></label><button type="submit">Save Profile</button><small class="note"></small></form>`;panel.querySelector('.back').onclick=()=>{root.remove();openProfile()};panel.querySelector('form').onsubmit=async e=>{e.preventDefault();const vals=Object.fromEntries(new FormData(e.currentTarget).entries());const {error}=await supabase.from('player_profiles').upsert({user_id:userId,...vals,updated_at:new Date().toISOString()},{onConflict:'user_id'});panel.querySelector('.note').textContent=error?'Could not save.':'Saved ✓'};}
async function showRefs(root,userId){const panel=root.querySelector('.core-profile-panel');panel.innerHTML=`<button class="back">← Profile</button><span class="eyebrow">REFLECTIONS</span><h2>My Reflections</h2><div class="list">Loading…</div>`;panel.querySelector('.back').onclick=()=>{root.remove();openProfile()};const {data,error}=await supabase.from('daily_reflections').select('*').eq('user_id',userId).order('created_at',{ascending:false}).limit(200);panel.querySelector('.list').innerHTML=error?'Could not load reflections.':(data||[]).map(r=>`<article style="padding:12px 0;border-top:1px solid #333"><strong style="color:#ef8a3f">${esc(r.reflection_date||'')} · ${esc(r.scripture_reference||'Scripture')}</strong><p style="color:#aaa">${esc(r.question||'')}</p><span>${esc(r.response||'')}</span></article>`).join('')||'No saved reflections yet.';}

async function renderChapelRoster(){const card=document.querySelector('.feature-event');if(!card)return;const {data:event}=await supabase.from('chapel_events').select('id').gte('starts_at',new Date(Date.now()-2*3600000).toISOString()).order('starts_at',{ascending:true}).limit(1).maybeSingle();if(!event)return;let rows=[];const rpc=await supabase.rpc('chapel_rsvp_roster',{p_event_id:event.id});if(!rpc.error)rows=rpc.data||[];else{const [{data:r},{data:p}]=await Promise.all([supabase.from('rsvps').select('user_id,attending').eq('event_id',event.id),supabase.from('profiles').select('id,display_name,jersey_number,role')]);const map=new Map((p||[]).map(x=>[x.id,x]));rows=(r||[]).map(x=>({...x,...map.get(x.user_id)})).filter(x=>x.display_name)}const seenYes=new Set(),seenNo=new Set(),yes=[],no=[];for(const r of rows){const key=r.role==='admin'?'admin':r.user_id||r.id;if(r.attending===true&&!seenYes.has(key)){seenYes.add(key);yes.push(r)}if(r.attending===false&&!seenNo.has(key)){seenNo.add(key);no.push(r)}}let box=card.querySelector('.core-rsvp');if(!box){box=document.createElement('div');box.className='core-rsvp';card.appendChild(box)}box.innerHTML=`<h3>Chapel RSVP</h3><div class="core-rsvp-summary"><b>${yes.length} coming</b><span>${no.length} can't make it</span></div><div class="core-rsvp-list">${yes.length?yes.map(r=>`<span>✓ ${esc(r.role==='admin'?'Pastor Ryan':r.display_name)}${r.role!=='admin'&&r.jersey_number?` #${esc(r.jersey_number)}`:''}</span>`).join(''):'<span>No one has RSVP’d yet.</span>'}</div>${no.length?`<details><summary>Can't make it (${no.length})</summary>${no.map(r=>`<div>${esc(r.role==='admin'?'Pastor Ryan':r.display_name)}</div>`).join('')}</details>`:''}`}

addStyles();
document.addEventListener('input',e=>{if(e.target?.placeholder==='Last name')requestAnimationFrame(fixAdminJersey)},true);
document.addEventListener('click',e=>{const avatar=e.target.closest?.('.header-actions .avatar');if(!avatar)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openProfile()},true);
const observer=new MutationObserver(()=>{fixAdminJersey();renderChapelRoster()});observer.observe(document.documentElement,{childList:true,subtree:true});
setInterval(()=>{fixAdminJersey();renderChapelRoster()},700);
fixAdminJersey();renderChapelRoster();