import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { createClient } from '@supabase/supabase-js';
import './styles.css';

const SUPABASE_URL = 'https://jpfnhwolttfisawfthbf.supabase.co';
const SUPABASE_KEY = 'sb_publishable_vsHZotBHUEePBvunVgTWWQ_fIImlhYY';
const supabase = createClient(SUPABASE_URL, SUPABASE_KEY, { auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true, storageKey: 'lancers-chapel-session' }});
const LOGO='/lancers-logo.png';
const DEFAULT_DEVOTION={reference:'JOSHUA 1:9',verse:'Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.',title:'Steady in the moment',body:'Pressure does not mean God has left the room. Courage is trusting His presence in the moment.',question:'Where do you need to compete from trust instead of fear?'};
const games=[];
function chicagoDay(date=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).format(date)}
function chicagoClock(date=new Date()){return new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',hour:'numeric',minute:'2-digit'}).format(date)}
function chicagoLong(date=new Date()){return new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',weekday:'long',month:'long',day:'numeric'}).format(date)}
function eventText(iso){return new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(iso))}
function initials(name='Player'){return name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function formatTime(iso){return new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',hour:'numeric',minute:'2-digit'}).format(new Date(iso))}
function Gate({onReady}){const[form,setForm]=useState({first:'',last:'',jersey:'',code:''});const[busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(e){e.preventDefault();setBusy(true);setError('');try{const{data,error:fnError}=await supabase.functions.invoke('team-entry',{body:{firstName:form.first.trim(),lastName:form.last.trim(),jerseyNumber:form.last.trim().toLowerCase()==='lingbloom'?'100':form.jersey.trim(),teamCode:form.code.trim()}});if(fnError)throw fnError;if(!data?.email||!data?.password)throw new Error(data?.error||'Could not sign in.');const{error:authError}=await supabase.auth.signInWithPassword({email:data.email,password:data.password});if(authError)throw authError;onReady()}catch(err){setError(err.message||'Could not sign in.')}finally{setBusy(false)}}return <main className="gate"><img src={LOGO} alt="Omaha Lancers"/><span>OMAHA LANCERS</span><h1>Chapel</h1><p>Scripture. Team connection. A place to check in and stay connected with Pastor Ryan.</p><form onSubmit={submit}><div className="name-row"><input required placeholder="First name" value={form.first} onChange={e=>setForm({...form,first:e.target.value})}/><input required placeholder="Last name" value={form.last} onChange={e=>setForm({...form,last:e.target.value})}/></div><input required placeholder="Jersey number" value={form.jersey} onChange={e=>setForm({...form,jersey:e.target.value})}/><input required placeholder="Team code" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/><button disabled={busy}>{busy?'Signing in…':'Enter Lancers Chapel'}</button></form>{error&&<div className="gate-notice">{error}</div>}</main>}
function Home({user,devotion,event,checkins,onRefresh}){const[now,setNow]=useState(new Date());useEffect(()=>{const i=setInterval(()=>setNow(new Date()),30000);return()=>clearInterval(i)},[]);const today=chicagoDay(now);const checkedToday=checkins.some(c=>c.checkin_day===today||chicagoDay(new Date(c.created_at))===today);const streak=useMemo(()=>{const days=[...new Set(checkins.map(c=>c.checkin_day||chicagoDay(new Date(c.created_at))))].sort().reverse();let count=0,cursor=new Date(`${today}T12:00:00`);if(!days.includes(today))cursor.setDate(cursor.getDate()-1);for(const day of days){if(day===chicagoDay(cursor)){count++;cursor.setDate(cursor.getDate()-1)}else if(day<chicagoDay(cursor))break}return count},[checkins,today]);async function checkin(mood){if(checkedToday)return;await supabase.from('checkins').insert({user_id:user.id,mood});await onRefresh()}const d=devotion||DEFAULT_DEVOTION;return <><section className="welcome"><img src={LOGO}/><div className="home-clock"><strong>{chicagoClock(now)}</strong><p>{chicagoLong(now)}</p></div><h1>Ready for today.</h1><span>{user.display_name}</span></section><article className="word-card"><div className="word-meta"><span>TODAY'S WORD</span><span>{d.reference}</span></div><p className="verse">“{d.verse}”</p><p className="reference">{d.reference}</p><div className="devotion"><h2>{d.title}</h2><p>{d.body}</p><strong>Think about it:</strong><p>{d.question}</p></div></article><article className="streak-card"><div className="streak-flame">🔥</div><div><span className="eyebrow">CURRENT STREAK</span><h2>{streak} days</h2></div></article><section className={`checkin ${checkedToday?'done':''}`}><span className="eyebrow">DAILY CHECK-IN</span><h2>{checkedToday?'You’re checked in for today ✓':'How are you doing today?'}</h2>{!checkedToday&&<div className="moods"><button onClick={()=>checkin('Good')}>Good</button><button onClick={()=>checkin('Okay')}>Okay</button><button onClick={()=>checkin('Talk')}>Need to talk</button></div>}</section></>}
function Chapel(){return <section className="page-section"><h1>Chapel</h1></section>}
function Chat(){return <section className="page-section chat-page"><h1>Chat</h1></section>}
function Games(){return <section className="games-page"></section>}
function PastorPage(){return <section className="private-page"><h1>Pastor Ryan</h1></section>}
function Admin(){return <section className="admin-live"><h1>Lancers Chapel Admin</h1></section>}
function App(){const[session,setSession]=useState(null),[user,setUser]=useState(null),[loading,setLoading]=useState(true),[tab,setTab]=useState('home'),[devotion,setDevotion]=useState(null),[event,setEvent]=useState(null),[checkins,setCheckins]=useState([]),[players,setPlayers]=useState([]);const isAdmin=user?.role==='admin';async function loadSession(){const{data:{session:s}}=await supabase.auth.getSession();setSession(s);if(!s){setUser(null);setLoading(false);return}const{data:p}=await supabase.from('profiles').select('*').eq('id',s.user.id).single();setUser(p);await loadData(p);setLoading(false)}async function loadData(p=user){if(!p)return;const day=chicagoDay();const[d,e,c]=await Promise.all([supabase.from('devotions').select('*').eq('published',true).lte('devotion_date',day).order('devotion_date',{ascending:false}).limit(1).maybeSingle(),supabase.from('chapel_events').select('*').gte('starts_at',new Date(Date.now()-7200000).toISOString()).order('starts_at',{ascending:true}).limit(1).maybeSingle(),supabase.from('checkins').select('*').eq('user_id',p.id).order('created_at',{ascending:false}).limit(120)]);setDevotion(d.data);setEvent(e.data);setCheckins(c.data||[])}useEffect(()=>{loadSession()},[]);if(loading)return <div className="loading">Loading Lancers Chapel…</div>;if(!session||!user)return <Gate onReady={loadSession}/>;const nav=[['home','⌂','Scripture'],['chapel','✚','Chapel'],['chat','●','Chat'],['games','🏆','Badges'],[isAdmin?'admin':'pastor','◉',isAdmin?'Admin':'Pastor Ryan']];return <main className="app-shell"><header className="topbar"><button className="brand" onClick={()=>setTab('home')}><img src={LOGO}/><span><strong>LANCERS</strong><small>CHAPEL</small></span></button></header><div className="content">{tab==='home'&&<Home user={user} devotion={devotion} event={event} checkins={checkins} onRefresh={()=>loadData(user)}/>} {tab==='chapel'&&<Chapel/>} {tab==='chat'&&<Chat/>} {tab==='games'&&<Games/>} {tab==='pastor'&&<PastorPage/>} {tab==='admin'&&<Admin/>}</div><nav className="bottom-nav five">{nav.map(([key,icon,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}><span>{icon}</span>{label}</button>)}</nav></main>}
createRoot(document.getElementById('root')).render(<App/>);