import { createClient } from '@supabase/supabase-js';
const supabase=createClient('https://jpfnhwolttfisawfthbf.supabase.co','sb_publishable_vsHZotBHUEePBvunVgTWWQ_fIImlhYY',{auth:{persistSession:true,autoRefreshToken:true,storageKey:'lancers-chapel-session'}});
const CHECK=[{milestone:1,icon:'👋',name:'SHOWED UP'},{milestone:7,icon:'🎯',name:'CONSISTENT'},{milestone:10,icon:'💪',name:'TEN STRONG'},{milestone:30,icon:'🧱',name:'BUILT A RHYTHM'},{milestone:60,icon:'⚙️',name:'DIALED IN'},{milestone:75,icon:'🥇',name:'STEADFAST'},{milestone:100,icon:'💯',name:'100 STRONG'}];
const BIBLE=[{milestone:1,icon:'🌱',name:'PLANTED'},{milestone:7,icon:'📖',name:'ONE WEEK IN THE WORD'},{milestone:10,icon:'🪴',name:'ROOTED'},{milestone:30,icon:'🌳',name:'GROWING DEEP'},{milestone:60,icon:'🧭',name:'GUIDED BY THE WORD'},{milestone:75,icon:'⚔️',name:'SHARPENED'},{milestone:100,icon:'🪨',name:'BUILT ON THE ROCK'}];
const THREE=[{milestone:1,icon:'🟠',name:'FIRST STEP'},{milestone:7,icon:'🔥',name:'ONE WEEK'},{milestone:25,icon:'⚡',name:'LOCKED IN'},{milestone:40,icon:'🛡️',name:'BUILT DIFFERENT'},{milestone:50,icon:'🏆',name:'FIFTY STRONG'},{milestone:75,icon:'💎',name:'ALL IN'},{milestone:100,icon:'🐐',name:'GOAT'},{milestone:125,icon:'👑',name:'ELITE'},{milestone:150,icon:'🦁',name:'RELENTLESS'},{milestone:200,icon:'🏔️',name:'SUMMIT'}];
function chicagoDay(date=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).format(date)}
function streak(raw){const days=[...new Set(raw.filter(Boolean))].sort().reverse();const today=chicagoDay();let cursor=new Date(`${today}T12:00:00`),count=0;if(!days.includes(today))cursor.setDate(cursor.getDate()-1);for(const day of days){const expected=chicagoDay(cursor);if(day===expected){count++;cursor.setDate(cursor.getDate()-1)}else if(day<expected)break}return count}
function styles(){if(document.getElementById('trophy-room-css'))return;const s=document.createElement('style');s.id='trophy-room-css';s.textContent=`.trophy-room{padding:20px 16px 110px}.trophy-room h1{margin:0 0 4px;font-size:30px}.trophy-room>p{margin:0 0 18px;color:#999;font-size:12px}.trophy-group{background:#141414;border:1px solid #2d2d2d;border-radius:18px;padding:16px;margin-bottom:14px}.trophy-group.all-three{border-color:#5a351c;background:linear-gradient(145deg,#151515,#1c130d)}.trophy-group h2{font-size:12px;letter-spacing:.12em;color:#f47a22;margin:0 0 12px}.trophy-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.trophy{min-height:106px;border-radius:15px;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:10px 6px}.trophy.earned{border:1px solid #8b532b;background:linear-gradient(145deg,#28180d,#1d120b);box-shadow:0 0 18px rgba(244,122,34,.11),inset 0 0 0 1px #3a2416}.trophy.locked{border:1px solid #2d2d2d;background:#101010;opacity:.45;filter:grayscale(1)}.trophy .icon{font-size:32px}.trophy strong{font-size:8px;line-height:1.15;margin-top:8px}.trophy.earned strong{color:#f0c7a3}.trophy.locked strong{color:#777}.trophy small{font-size:8px;margin-top:4px;color:#8e735f}.trophy .status{font-size:7px;letter-spacing:.08em;margin-top:7px;font-weight:900}.trophy.earned .status{color:#f47a22}.trophy.locked .status{color:#666}`;document.head.appendChild(s)}
function grid(track,rows,current=0){const earned=new Set((rows||[]).map(r=>Number(r.milestone)));track.forEach(b=>{if(b.milestone<=current)earned.add(b.milestone)});return `<div class="trophy-grid">${track.map(b=>{const got=earned.has(b.milestone);return `<div class="trophy ${got?'earned':'locked'}"><span class="icon">${b.icon}</span><strong>${b.name}</strong><small>${b.milestone} day${b.milestone===1?'':'s'}</small><span class="status">${got?'EARNED':'LOCKED'}</span></div>`}).join('')}</div>`}
async function render(){styles();const gamesPage=document.querySelector('.games-page');if(!gamesPage)return;const {data:{session}}=await supabase.auth.getSession();if(!session)return;const uid=session.user.id;const [{data:check},{data:bible},{data:three},{data:checks}]=await Promise.all([supabase.from('streak_milestone_log').select('milestone').eq('user_id',uid),supabase.from('bible_streak_milestone_log').select('milestone').eq('user_id',uid),supabase.from('daily_three_milestone_log').select('milestone').eq('user_id',uid),supabase.from('checkins').select('checkin_day,created_at').eq('user_id',uid).order('created_at',{ascending:false}).limit(120)]);const checkDays=(checks||[]).map(c=>c.checkin_day||chicagoDay(new Date(c.created_at)));const master=streak(checkDays);gamesPage.innerHTML=`<section class="trophy-room"><h1>Badges</h1><p>Your wins. Your next targets. Earn it once, keep it forever.</p><div class="trophy-group"><h2>CHECK-IN</h2>${grid(CHECK,check,master)}</div><div class="trophy-group"><h2>BIBLE</h2>${grid(BIBLE,bible,master)}</div><div class="trophy-group all-three"><h2>ALL 3</h2>${grid(THREE,three,master)}</div><p>Earned badges stay unlocked even if a streak resets.</p></section>`}
function nav(){document.querySelectorAll('.bottom-nav button').forEach(b=>{const text=(b.textContent||'').trim().toLowerCase();if(text==='games'||text.includes('trophy')||text.includes('badges')){const icon=b.querySelector('span');if(icon)icon.textContent='🏆';const walker=document.createTreeWalker(b,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode()){const t=(n.textContent||'').trim().toLowerCase();if(t==='games'||t==='trophy room'||t==='badges')n.textContent='Badges'}}})}
let timer;function run(){nav();clearTimeout(timer);timer=setTimeout(render,60)}window.addEventListener('load',run);document.addEventListener('click',()=>setTimeout(run,50),true);new MutationObserver(()=>{nav();if(document.querySelector('.games-page')&&!document.querySelector('.trophy-room'))run()}).observe(document.documentElement,{childList:true,subtree:true});run();